# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b119728692436779719217ad4a65db1c0ff83f6f920e66d03b78ad5f425ec950f749526256a2a39d2339dbcbc44177d51a5f4031c1162a2d9d30243d4090b431

test:
  secret_key_base: 46ad25d449f2294bc607282899782184b39d4c1ced77461431c9dee1d253fcf8dd0b60f14a4379e78a973caec7a0169d7138c73cbc3c0062a0e8b043649bd088

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
